apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - serviceaccounts.yaml
  - runner-agent-runtime-rbac.yaml
  - harbor-api.yaml
  - synthetic-data-platform.yaml
  - harbor-runner.yaml
  - poddisruptionbudgets.yaml
  - horizontalpodautoscalers.yaml
