apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - networkpolicies.yaml

images:
  - name: example.tencentcloudcr.com/harbor-platform/harbor-api
    newName: change-me.tencentcloudcr.com/harbor-platform/harbor-api
    newTag: v0.0.0-replace-me
  - name: example.tencentcloudcr.com/harbor-platform/synthetic-data-platform-api
    newName: change-me.tencentcloudcr.com/harbor-platform/synthetic-data-platform-api
    newTag: v0.0.0-replace-me
  - name: example.tencentcloudcr.com/harbor-platform/synthetic-data-platform-web
    newName: change-me.tencentcloudcr.com/harbor-platform/synthetic-data-platform-web
    newTag: v0.0.0-replace-me
  - name: example.tencentcloudcr.com/harbor-platform/harbor-runner
    newName: change-me.tencentcloudcr.com/harbor-platform/harbor-runner
    newTag: v0.0.0-replace-me
